#!/usr/bin/env python3
"""Generate the camera gallery's compact 16x16 GB2312 bitmap font."""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FONT_PATH = Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc")
FONT_INDEX = 2  # Noto Sans CJK SC Regular
FONT_SIZE = 15
GLYPH_SIZE = 16
THRESHOLD = 96
OUTPUT = Path(__file__).with_name("camera_gallery_zh_font.c")
EXTRA_CHARACTERS = "，。！？；：、‘’“”（）《》【】—…"


def gb2312_characters() -> list[str]:
    characters: set[str] = set(EXTRA_CHARACTERS)
    for lead in range(0xA1, 0xF8):
        for trail in range(0xA1, 0xFF):
            try:
                character = bytes((lead, trail)).decode("gb2312")
            except UnicodeDecodeError:
                continue
            if len(character) == 1 and ord(character) <= 0xFFFF:
                characters.add(character)
    return sorted(characters, key=ord)


def glyph_rows(font: ImageFont.FreeTypeFont, character: str) -> list[int]:
    image = Image.new("L", (GLYPH_SIZE, GLYPH_SIZE), 0)
    draw = ImageDraw.Draw(image)
    # A fixed baseline keeps Chinese punctuation at its natural vertical position.
    draw.text((0, -4), character, font=font, fill=255)
    rows: list[int] = []
    for y in range(GLYPH_SIZE):
        value = 0
        for x in range(GLYPH_SIZE):
            if image.getpixel((x, y)) >= THRESHOLD:
                value |= 0x8000 >> x
        rows.append(value)
    return rows


def generate() -> str:
    if not FONT_PATH.is_file():
        raise SystemExit(f"font not found: {FONT_PATH}")

    font = ImageFont.truetype(str(FONT_PATH), FONT_SIZE, index=FONT_INDEX)
    characters = gb2312_characters()
    entries = []
    for character in characters:
        rows = ", ".join(f"0x{row:04x}" for row in glyph_rows(font, character))
        entries.append(f"  {{0x{ord(character):04x}, {{{rows}}}}}, /* {character} */")

    return f'''/****************************************************************************
 * apps/examples/camera_gallery/camera_gallery_zh_font.c
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by generate_zh_font.py from Noto Sans CJK SC, distributed under
 * the SIL Open Font License 1.1.  Contains GB2312 characters and common
 * Chinese punctuation as 16x16 one-bit glyphs.
 ****************************************************************************/

#include <nuttx/config.h>

#include <stddef.h>
#include <stdint.h>

#include "camera_gallery.h"

struct camera_gallery_zh_glyph_s
{{
  uint16_t codepoint;
  uint16_t rows[CAMERA_GALLERY_ZH_FONT_HEIGHT];
}};

static const struct camera_gallery_zh_glyph_s g_camera_gallery_zh_glyphs[] =
{{
{chr(10).join(entries)}
}};

FAR const uint16_t *camera_gallery_zh_glyph(uint32_t codepoint)
{{
  size_t low = 0;
  size_t high = sizeof(g_camera_gallery_zh_glyphs) /
                sizeof(g_camera_gallery_zh_glyphs[0]);

  if (codepoint > UINT16_MAX)
    {{
      return NULL;
    }}

  while (low < high)
    {{
      size_t middle = low + (high - low) / 2;
      uint16_t current = g_camera_gallery_zh_glyphs[middle].codepoint;

      if (current < codepoint)
        {{
          low = middle + 1;
        }}
      else
        {{
          high = middle;
        }}
    }}

  if (low < sizeof(g_camera_gallery_zh_glyphs) /
            sizeof(g_camera_gallery_zh_glyphs[0]) &&
      g_camera_gallery_zh_glyphs[low].codepoint == codepoint)
    {{
      return g_camera_gallery_zh_glyphs[low].rows;
    }}

  return NULL;
}}
'''


def main() -> None:
    content = generate()
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"generated {len(gb2312_characters())} glyphs in {OUTPUT}")


if __name__ == "__main__":
    main()
